package com.ts.phi.enums;

public enum QuestionType {
    IDLE,
    SPORTS_MODE_AGREE,
    NORMAL_MODE_AGREE,
    SWITCH_FEELING,
    AUTO_FEEDBACK,
    ADJUST_TRY_AGREE,
    CUSTOM_SPORTS_AGREE,
    RECOMMEND_FEATURE_AGREE,
    CUSTOM_MODE_FEEDBACK,
    WAIT_USER_FAVORITE_AGREE
}